#!/usr/bin/env python
# encoding: utf-8
"""
usage: sleep seconds
"""

from sys import argv, stderr, stdout
from time import sleep, time


def _main():
    # get number of seconds
    try:
        seconds = float(argv[1])
    except Exception:
        print >> stderr, __doc__[1:-1]
        exit(1)

    # get target time
    target_time = time() + seconds

    # print right-aligned string and go back to the beginning of a line
    line_length = len('%.1f' % seconds) + 4
    def put(s=''):
        print ('%s%s\r' % (' ' * (line_length - len(s)), s)),
        stdout.flush()

    # show countdown timer
    while seconds > 0:
        put('%.1f' % seconds)
        sleep(0.1)
        seconds = target_time - time()

    # clear the screen
    put()

if __name__ == '__main__':
    _main()
